### ISSUE TITLE
Having trouble starting app

### ISSUE THREAD

**Issue by dhoule** [dhoule/reacttest#3]
Running `rails s` & `rails c` gives the following error:
```
Running via Spring preloader in process 95360
/Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': dlopen(/Users/dhoule/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/x86_64-darwin16/readline.bundle, 9): Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib (LoadError)
  Referenced from: /Users/dhoule/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/x86_64-darwin16/readline.bundle
  Reason: image not found - /Users/dhoule/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/x86_64-darwin16/readline.bundle
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	from /Users/dhoule/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/irb/completion.rb:10:in `<main>'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/railties-5.2.3/lib/rails/commands/console/console_command.rb:4:in `<main>'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/railties-5.2.3/lib/rails/command/behavior.rb:84:in `block (2 levels) in lookup'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/railties-5.2.3/lib/rails/command/behavior.rb:80:in `each'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/railties-5.2.3/lib/rails/command/behavior.rb:80:in `block in lookup'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/railties-5.2.3/lib/rails/command/behavior.rb:79:in `each'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/railties-5.2.3/lib/rails/command/behavior.rb:79:in `lookup'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/railties-5.2.3/lib/rails/command.rb:70:in `find_by_namespace'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/railties-5.2.3/lib/rails/command.rb:44:in `invoke'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	from /Users/dhoule/Github/reacttest/bin/rails:9:in `<main>'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/dhoule/.rvm/gems/ruby-2.3.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
	from /Users/dhoule/.rvm/rubies/ruby-2.3.5/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/dhoule/.rvm/rubies/ruby-2.3.5/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by dhoule** [comment]
Found [this](https://stackoverflow.com/questions/54261455/library-not-loaded-usr-local-opt-readline-lib-libreadline-7-dylib) on Stackoverflow. Running the following commands got the RoR server up and running:

```
cd /usr/local/opt/readline/lib 
ln -s libreadline.8.0.dylib libreadline.7.dylib
```
